### ISSUE TITLE
query for files needs levels

### ISSUE THREAD

**Issue by maasencioh** [mylims/mylims#116]
- now everything is queried, the idea will be only query the specific level
- add depth to fileSync
- escape regular expression for the query
- `escape-string-regexp`

**Comment by maasencioh** [comment]
## Objective

The idea is to be able to query information from the directories inside a given folder, for example, having the following files:

```
A/A/1.txt
A/A/2.txt
A/B/1.txt
A/B/2.txt
A/C/D/E/2.txt
A/1.txt
```

A query in the `/A` folder will return `A/1.txt` and the directories `A/A`, `A/B` and `A/C`.
For each dir the size is the sum of the inner files, and the date is the latest of the inner date files.

## Problem
I haven't found a way of create a projection, in order to group by dir

```
db.files.aggregate([
  { $match: { "_id.relativePath": /^A/, level: { $gte: 3 } } },
  { $project: { dirname: { TODO } } },
  { $group: { _id: "$dirname", size: { $sum:  "$revisions.0.size" } } },
])
```

## Proposals
1. **mapReduce**: A map-reduce strategy can work out, knowing the desired level in javascript we can get the ith element of the path. The problems are the complexity added to the search for the `mapReduce` and that we don't know the separator of the system (could be windows or unix)
2. **use path: string[] instead level: number**: Like this we could write our aggregation something like this:

```
db.files.aggregate([
  { $match: { "_id.relativePath": /^A/, path: { $size: { $gte: 3 } } } },
  { $group: { _id: "$path.3", size: { $sum:  "$revisions.0.size" } } },
])
```

**Comment by targos** [comment]
> we don't know the separator of the system (could be windows or unix)

The separator is known as `require('path').sep`

It was decided that we would not support sharing a database between windows and unix

**Comment by targos** [comment]
I don't think we absolutely need to know what's in a folder before we open it, if it can help with the implementation.

**Comment by maasencioh** [comment]
> The separator is known as require('path').sep

I was thinking more in the aggregation, that will require that the system is mounted in the same os, but that's a minor detail, considering that there's no split method for strings (that I'm aware of)

> I don't think we absolutely need to know what's in a folder before we open it, if it can help with the implementation.

That simplyfies indeed the process, but I'll want in any case that the database handles the grouping section, in order to avoid an unnecessary big fetch

**Comment by targos** [comment]
In any case, an aggregation pipeline must be used. map-reduce would be too slow.
