### ISSUE TITLE
B1505 processor

### ISSUE THREAD

**Issue by maasencioh** [mylims/mylims#143]
example of a processor workflow

**Comment by maasencioh** [comment]
@targos @lpatiny when a processor finishes processing a file from an event it will create a new file in the `fileSync.files` collection, where should it be linked to?

1. `fileSync.syncFiles` in a new `revisions.0.topics.[topic]` field save the id
2. `fileSync.files` in a new `topics.[topic]` field save the id
3. `events` in the `processors.[index].history.0.id`

For me, the query in 3 is too complex, and I personally prefer the first one, but I will like to have your opinions

**Comment by targos** [comment]
Why would a processor create a file in the fileSync.files collection?

**Comment by maasencioh** [comment]
Good point, but still the point for where to create the foreign key for it

**Comment by maasencioh** [comment]
Moved here https://github.com/mylims/processor-iv
