### ISSUE TITLE
How to have hierarchy in samples ?

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#203]
sampleId is currently an array of string

It seems useful that if a sample is a child of another sample we just append a string to the previous array.

This will allow to display the hierarchy of samples.

**Comment by maasencioh** [comment]
sounds great to me, but will it be compatible with the project where you have this `sampleCode`?

**Comment by targos** [comment]
It would be a good convention, but I don't think hierarchy should only be based on the sample id.

**Comment by maasencioh** [comment]
Course for MongoDB relationships https://university.mongodb.com/courses/M001/about

**Comment by lpatiny** [comment]
Initially we thought about creating experiments that has X samples as input and Y samples as output. This is still probably something we will have to implement.

How to store hierarchy ?

`['wafer', 'sample', 'subsample']`

```
{
  'wafer': 'ABC',
  'sample': 'F1',
  'subsample': 'F1.2',
}
```

Another proposal from Miguel is to create one specific collection per kind of samples. Advantages:
- Layout are directly related to the kind
- Meta information is enforced depending the collection
- Measurements should be linked to collection + UUID (DBRef ?)


@targos. What is the best way to deal with hierarchy of sample. Seems to me that having a different collection per kind of sample (Wafter, Sample, ...) is a good idea.

Should a sample store an array of children as well as the parents ?

```
children: [ObjectID],
parents: [ObjectID direct parent, ObjectID parent + 1 ...]
```

**Comment by targos** [comment]
```
    parents(sample, params) {
      return paginateConnection(Sample, params, {
        _id: { $in: sample.parents },
      });
    },
    children(sample, params) {
      return paginateConnection(Sample, params, {
        parents: sample.id,
      });
    },
```

If you need to follow the hierarchy, MongoDB has a $graphLookup operator.
