### ISSUE TITLE
General information about samples

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#204]
- id (10 characters)
- kind: string (Wafer, Sample, SubSample)
- description
- labels: string[]
- meta{}: value: string, boolean, number or string[]
- attachments[]

I think we could decide in some general preferences the key / value that is allowed as well as the type of the value. Those values could define of the kind.

@maasencioh Could you add some concrete example that you would define for `wafer` and `sample` ?

@stropitek Is there something we could reuse to define those preferences for the parameters ?

@stropitek @targos do you think it is ok to have this parameters property in which the value could be 4 different types ?

**Comment by maasencioh** [comment]
1. What is a parameter on a sample?
2. A different sample should have a different collection (as currently is done at measurements)?

**Comment by stropitek** [comment]
@lpatiny can you define what a "parameter" is?

I presume you want start a discussion about how to define custom fields on samples? We have made something elsewhere but I'm not sure it can be used as a starting point here.

**Comment by maasencioh** [comment]
## Wafer
* waferName: "#0320"
* purpose: "Growth on SAM optimization"
* heterostructure: "GaN"
* substrate: "ScAlMgO4"
* size: "Chip 9mm x 10mm"
* supplier: "ICMP"
* supplierWaferNumber: "C3558"
* epiStructure: "Long text describing EPI structure"
* project: "project name"
* location: "cleanroom"
* attachments: []
* comment: "Similar to C3555, despite thicker NL"
* tags: string[]

## Sample
* waferName: "#0251"
* sampleName: "A34"
* purpose: "diamond on GaN"
* heterostructure: "AlGaN/GaN"
* status: "Unprocessed" ("In fabrication", "Completed")
* attachments: []
* tags: string[]

**Comment by lpatiny** [comment]
Which values should come from a list ? Which fields should be suggested based on existing values in the database ?

**Comment by maasencioh** [comment]
epiStructure should be an HTML saved as an attachment, inline images as base64 images

**Comment by lpatiny** [comment]
Need to add a collection `SampleKinds`

- _id = What we put in kindProperty of Sample
- name: 'Wafer', ...
- description: ''
- color
- schema ? jsonSchema

Allowed kind of values:
- string
- boolean
- number
- string[]
