### ISSUE TITLE
At the level of the sample we should display chart

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#205]
We should be able to display and superimpose measurements from the sample list.

We need at the level of the sample to search for keywords.

**Comment by maasencioh** [comment]
> We need at the level of the sample to search for keywords.

Definitely, I was thinking to use a tags system, but I'm not sure if we should enforce some tags to be in the sample (for example at the level of the wafer, if it was a local recipe to know if it was successful or not)

> We should be able to display and superimpose measurements from the sample list.

What I understand is that only makes sense to superimpose measurements from the same sample (or previously selected samples)

**Comment by maasencioh** [comment]
This now only has sense from the device view

**Comment by maasencioh** [comment]
Closed for the wafers at the level #258
