### ISSUE TITLE
What to do on many columns?

### ISSUE THREAD

**Issue by maasencioh** [mylims/mylims#211]
@targos @lpatiny @stropitek in the case that a table does have too many columns, should we `truncate` content or allow a `x-scroll` ?

**Comment by targos** [comment]
What do you suggest?

**Comment by maasencioh** [comment]
In slims they do x-scroll, that plus the possibility to resize the columns, but I don't think that we are going to support this, isn't it?

**Comment by stropitek** [comment]
If the user chooses their column, and we don't know the nature of what is displayed (custom columns) it's hard for me to imagine how truncate could win over scroll... But it's not a binary choice so maybe you are able to think of alternative ways to handle this problem

**Comment by maasencioh** [comment]
Thank you guys for your opinion, at the end I opted out of scrolling
