### ISSUE TITLE
Create a template to create children

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#213]
A student should decide how to create children.

There should be also a way to create meta information to the children.

@maasencioh We need to discuss about this

**Comment by lpatiny** [comment]
![image](https://user-images.githubusercontent.com/1484241/151586002-04a6d2bc-fdd5-498d-b5be-093ee653d05c.png)

Template shared at the level of the group

**Comment by maasencioh** [comment]
Creation formularies
- [ ] Create a table with editable fields, based on a template (ej. 6 inches wafer creates 36 children)
- [ ] If there's more than 1 kind of children, create a table for each one
- [ ] Possibility for changing all the column values, and unselect some rows of this

General tables
- [ ] Action buttons at the begining
