### ISSUE TITLE
Review of the best rich text editor in react

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#221]

**Comment by maasencioh** [comment]
I have the demos of the editors found in [this link](https://codesandbox.io/s/rich-text-editors-react-89vc6)

* [Draft.js](https://draftjs.org/)
  * Pros
    * Modulable
    * Seems to be stable
    * Exports JSON
  * Cons
    * So far so good
* [Quill.js](https://github.com/zenoamaro/react-quill)
  * Pros
    * Easy to configure
  * Cons
    * Exports only the HTML
    * not easy to add new components
* [Slate](https://docs.slatejs.org/)
  * Pros
    * Very modulable
    * Very active community
    * Resulting JSON is very light and intuitive
  * Cons
    * Is not possible to have a basic editor in a short time, everything needs to be defined and specified
* [Jodit](https://github.com/jodit/jodit-react)
  * Pros
    * Easy to configure
  * Cons
    * Exports only the HTML
    * not easy to add new components
    * onChange looses focus
* [Editor.js](https://github.com/Jungwoo-An/react-editor-js)
  * Pros
    * Modulable
    * Block editor, similar to Notion
  * Cons
    * It's a wrapper to a js library, so it feels like working with d3
    * Not easy to have the controlled version of the state, therefore to export the inner value

At the end the two best options for me are Draft.js or Slate.js (any other derivation of these two are similar in thery advantages or disadvantages). I really spent too much time on the creation of a basic example on Slate, but is really a very low level library, therefore everything is possible to be defined, but it takes a very long time to do anything.

I'll propose Draft.js or [react draft wyswyg](https://jpuri.github.io/react-draft-wysiwyg/#/)

**Comment by targos** [comment]
I'm a bit worried about Draft.js because it doesn't seem very maintained. Last release was on Aug 13th, 2020.

**Comment by maasencioh** [comment]
Yet it has regular commits, I think that they are really careful on what they release, which makes slow any feature request but makes a stable choice. Slate indeed has a lot more movement, but I'm still not sure that it will make it a better option.

**Comment by targos** [comment]
About Slate:

> Is not possible to have a basic editor in a short time, everything needs to be defined and specified

I agree it can be a con depending on the context, but I think that for us it's a good thing to have a low-level API that allows us to do exactly what we want.

**Comment by targos** [comment]
It also seems to me like the JSON output from Slate is much more understandable (Meaning we could easily create Slate-compatible input using JavaScript).

**Comment by maasencioh** [comment]
That was a big pro from Slate, I really enjoyed their JSON output. But we really need it at that low level?

**Comment by targos** [comment]
https://jkrsp.com/slate-js-vs-draft-js/

The fact that only Slate allows a nested structure seems like a huge pro to me.

**Comment by maasencioh** [comment]
- How to add an image through drag and drop
- Remove code and quotes
- ~Add storybook to front~ not for now
- Define API (value, onChange)
- Add a wrapper for RHF

**Comment by lpatiny** [comment]
Based on Michael comment:

https://plate.udecode.io/
Maybe this is interesting?
There are a lot of plugins
Question is whether it is still configurable enough for us
