### ISSUE TITLE
Write email with Elison in copy to check how to get the data from slims

### ISSUE THREAD

**Issue by lpatiny** [mylims/mylims#223]

**Comment by maasencioh** [comment]
Done, waiting for updates

**Comment by maasencioh** [comment]
These are the possibilities, we already have access to what we need

<img width="596" alt="image" src="https://user-images.githubusercontent.com/7273940/152132557-e0f24659-0eb3-47ee-b8be-19d31a8c5c46.png">

**Comment by lpatiny** [comment]
Will need to check what returns all the api points. Seems quite low level
